// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theseus.Infrastructure.DbContexts;

#nullable disable

namespace Theseus.Infrastructure.Migrations
{
    [DbContext(typeof(TheseusDbContext))]
    [Migration("20231031143343_ExamSets")]
    partial class ExamSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamSetDtoMazeDto", b =>
                {
                    b.Property<Guid>("ExamSetsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MazeDtosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExamSetsId", "MazeDtosId");

                    b.HasIndex("MazeDtosId");

                    b.ToTable("ExamSetDtoMazeDto");
                });

            modelBuilder.Entity("Theseus.Infrastructure.Dtos.ExamSetDto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ExamSets");
                });

            modelBuilder.Entity("Theseus.Infrastructure.Dtos.MazeDto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("EndDirection")
                        .HasColumnType("tinyint");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<byte[]>("Solution")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SolutionStartColumn")
                        .HasColumnType("int");

                    b.Property<int>("SolutionStartRow")
                        .HasColumnType("int");

                    b.Property<byte>("StartDirection")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("Structure")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mazes");
                });

            modelBuilder.Entity("ExamSetDtoMazeDto", b =>
                {
                    b.HasOne("Theseus.Infrastructure.Dtos.ExamSetDto", null)
                        .WithMany()
                        .HasForeignKey("ExamSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theseus.Infrastructure.Dtos.MazeDto", null)
                        .WithMany()
                        .HasForeignKey("MazeDtosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
